spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.aurora.backend: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: logs/aurora-backend.log
    max-size: 10MB
    max-history: 30

# Langchain4j
langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_AI_KEY}
      model-name: gemini-2.5-flash
      log-requests-and-responses: true
    streaming-chat-model:
      api-key: ${GEMINI_AI_KEY}
      model-name: gemini-2.5-flash
      log-requests-and-responses: true
    embedding-model:
      api-key: ${GEMINI_AI_KEY}
      model-name: text-embedding-004
      output-dimensionality: 768
      log-requests-and-responses: false