spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/aurora_hotel
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    com.aurora.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

# Langchain4j
langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_AI_KEY}
      model-name: gemini-2.5-flash
      log-requests-and-responses: true
    streaming-chat-model:
      api-key: ${GEMINI_AI_KEY}
      model-name: gemini-2.5-flash
      log-requests-and-responses: true
    embedding-model:
      api-key: ${GEMINI_AI_KEY}
      model-name: text-embedding-004
      output-dimensionality: 768
      log-requests-and-responses: false